### ISSUE TITLE
Blankscreen after Installation

### ISSUE THREAD

**Issue by m-imran79** [ajpalok/bWAPP#1]
Hello,

I am trying to install bWAPP on latest Kali Linux 2022.3 64bit  version running on VMPlayer 17. At the end of installation, were we reach to "http://localhost/bWAPP/install.php" and then click Here to install, my firefox browser screen goes blank. In the url I see "http://localhost/bWAPP/install.php?install=yes" with the Blankscreen. 

Am I doing something wrong? I am following this tutorial to install bWAPP (https://amanbytes.com/install-bwapp-in-linux/)

![bWAPP install](https://user-images.githubusercontent.com/23695247/206552580-bc19ece4-72a8-4d92-bc17-660bb1f58971.PNG)

![bWAPP installation error](https://user-images.githubusercontent.com/23695247/206552579-e9b3ac1b-bde8-42d3-a49d-3a13df50d3b9.PNG)

**Comment by ajpalok** [comment]
Did you configured your Database properly with BWAPP? Sometimes This problem occurs because of not finding database connection and that causes the blank screen. Sometimes port number is required for database URL like in MySQL, Database URL have to be `localhost:3306` in `/admin/settings.php`

**Comment by m-imran79** [comment]
@ajpalok Thank you for replying. I have checked, then changed localhost to localhost:3306 in settings.php file, but it problem remains the same. Secondly, I manually created the database bWAPP, and later tried to run the installation from the Installation page, but then I get the message that database BWAPP already exists. So it means I have no database connection error as you suspected. 

Here is the /admin/settings.php file. 

```
<?php

// Database connection settings
$db_server = "localhost";
$db_username = "user";
$db_password = "pass";
$db_name = "bWAPP";

// SQLite database name
$db_sqlite = "db/bwapp.sqlite";

// SMTP settings
$smtp_sender = "bwapp@mailinator.com";
$smtp_recipient = "bwapp@mailinator.com";
$smtp_server = "";

// A.I.M.
// A.I.M., or Authentication Is Missing, is a no-authentication mode
// It can be used for testing web scanners and crawlers
// Steps to crawl all pages, and to detect all vulnerabilities without authentication:
//   1. Change the IP address(es) in this file to the IP address(es) of your tool(s)
//   2. Point your web scanners, crawlers or attack tools to this URL: http://[bWAPP-IP]/bWAPP/aim.php
//   3. Push the button: all hell breaks loose...
$AIM_IPs = array("6.6.6.6", "6.6.6.7", "6.6.6.8", "10.0.1.66");
$AIM_subnet = "6.6.6.0/30";
//
// Add here the files that could break bWAPP or your web server in the A.I.M. mode
$AIM_exclusions = array("aim.php", "ba_logout.php", "cs_validation.php", "csrf_1.php", "http_verb_tampering.php", "ldap_connect.php", "ldapi.php", "portal.php", "sm_dos_2.php", "sm_obu_files.php");

// Evil bee mode
// All bWAPP security levels are bypassed in this mode by using a fixed cookie (security_level: 666)
// It can be combined with the A.I.M. mode, your web scanner will ONLY detect the vulnerabilities
// Evil bees are HUNGRY :)
// Possible values: 0 (off) or 1 (on)
$evil_bee = 0;

// Static credentials
// These credentials are used on some PHP pages
$login = "bee";
$password = "bug";

?>
```

**Comment by ajpalok** [comment]
I've tried to reinstall it and worked fine by using MySQL DB server. By the way, After facing the blank screen, was you able to login with "bee" account with password "bug"?

**Comment by m-imran79** [comment]
Thank you for responding. Yes I tried to login page but still it shows the blankpage. I searched internet and someone suggested to check error log. So I went to var/log/apache2/error.log. It was showing the following error:

`[Sun Dec 11 06:02:42.634393 2022] [php:error] [pid 38247] [client 127.0.0.1:36316] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown database 'bWAPP' in /var/www/html/bWAPP/install.php:40\nStack trace:\n#0 /var/www/html/bWAPP/install.php(40): mysqli_select_db()\n#1 {main}\n  thrown in /var/www/html/bWAPP/install.php on line 40, referer: http://localhost/bWAPP/install.php/`

If you have time, we can connect over skype, or Google Meet and I can share my screen. 

Open to any suggestions.

**Comment by ajpalok** [comment]
The fact is I'm not the author of the code (Just re-uploaded the code to make it easy to download), that's why I can't provide proper solution here at this moment, I tried to resolve the same issue which I also faced in first time installation about a year ago but that solution is not your case which I found from your provided meta data. You may contact with the author at [MME_IT](https://twitter.com/MME_IT). Sorry for the inconveniences.

**Comment by mjattu** [comment]
> Thank you for responding. Yes I tried to login page but still it shows the blankpage. I searched internet and someone suggested to check error log. So I went to var/log/apache2/error.log. It was showing the following error:
> 
> `[Sun Dec 11 06:02:42.634393 2022] [php:error] [pid 38247] [client 127.0.0.1:36316] PHP Fatal error: Uncaught mysqli_sql_exception: Unknown database 'bWAPP' in /var/www/html/bWAPP/install.php:40\nStack trace:\n#0 /var/www/html/bWAPP/install.php(40): mysqli_select_db()\n#1 {main}\n thrown in /var/www/html/bWAPP/install.php on line 40, referer: http://localhost/bWAPP/install.php/`
> 
> If you have time, we can connect over skype, or Google Meet and I can share my screen.
> 
> Open to any suggestions.

Hey, Did you resolved the issue?
